/** Capability IDs from `solver/pb/caps.go`, used to populate `OpMetadata.caps`. */
export const Cap = {
  SourceImage: "source.image",
  SourceImageResolveMode: "source.image.resolvemode",
  SourceImageLayerLimit: "source.image.layerlimit",
  SourceLocal: "source.local",
  SourceLocalUnique: "source.local.unique",
  SourceLocalSessionID: "source.local.sessionid",
  SourceLocalIncludePatterns: "source.local.includepatterns",
  SourceLocalFollowPaths: "source.local.followpaths",
  SourceLocalExcludePatterns: "source.local.excludepatterns",
  SourceLocalSharedKeyHint: "source.local.sharedkeyhint",
  SourceLocalDiffer: "source.local.differ",
  SourceGit: "source.git",
  SourceGitKeepDir: "source.git.keepgitdir",
  SourceGitFullURL: "source.git.fullurl",
  SourceGitSubdir: "source.git.subdir",
  SourceGitChecksum: "source.git.checksum",
  SourceHTTP: "source.http",
  SourceHTTPChecksum: "source.http.checksum",
  SourceHTTPPerm: "source.http.perm",
  SourceHTTPUIDGID: "soruce.http.uidgid",
  ExecMetaBase: "exec.meta.base",
  ExecMetaCgroupParent: "exec.meta.cgroup.parent",
  ExecMetaNetwork: "exec.meta.network",
  ExecMetaProxy: "exec.meta.proxyenv",
  ExecMetaSecurity: "exec.meta.security",
  ExecMetaSetsDefaultPath: "exec.meta.setsdefaultpath",
  ExecMetaUlimit: "exec.meta.ulimit",
  ExecMetaCDI: "exec.meta.cdi",
  ExecMetaRemoveMountStubsRecursive: "exec.meta.removemountstubs.recursive",
  ExecMetaLinuxResources: "exec.meta.linux.resources",
  ExecMountBind: "exec.mount.bind",
  ExecMountBindReadWriteNoOutput: "exec.mount.bind.readwrite-nooutput",
  ExecMountCache: "exec.mount.cache",
  ExecMountCacheSharing: "exec.mount.cache.sharing",
  ExecMountSelector: "exec.mount.selector",
  ExecMountTmpfs: "exec.mount.tmpfs",
  ExecMountTmpfsSize: "exec.mount.tmpfs.size",
  ExecMountSecret: "exec.mount.secret",
  ExecMountSSH: "exec.mount.ssh",
  ExecSecretEnv: "exec.secretenv",
  ExecValidExitCode: "exec.validexitcode",
  FileBase: "file.base",
  FileRmWildcard: "file.rm.wildcard",
  FileCopyIncludeExcludePatterns: "file.copy.includeexcludepatterns",
  FileCopyModeStringFormat: "file.copy.modestring",
  FileSymlinkCreate: "file.symlink.create",
  Constraints: "constraints",
  Platform: "platform",
  MetaIgnoreCache: "meta.ignorecache",
  MetaDescription: "meta.description",
  MetaExportCache: "meta.exportcache",
  MergeOp: "mergeop",
  DiffOp: "diffop",
} as const;

export type CapID = (typeof Cap)[keyof typeof Cap];
